- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.0.2.0/24
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        owner: root

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      args:
        chdir: $HOME
        
    - name: Get the token for joining the worker nodes
      become: yes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"


    - name: Copy join command to local file.
      become: no
        #become_user: root
      delegate_to: localhost
      copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}" 
        dest : "./kubernetes_join_command" 
        mode: 0777
