- name: nfs installation
  hosts: 
    - master
    - worker1
    - worker2
  become: yes
  tasks:

    - name: add nfs-server host 
      blockinfile:
         path: "/etc/hosts"
         block: |
                172.16.1.4 nfs-server

    - name: Create shared directoy
      file:
        path: /mnt/shared
        state: directory

    - name: start nfs-client.target
      systemd:
        name: nfs-client.target
        state: started
        enabled: yes

    - name: mount filesystem
      mount:
        path: /mnt/shared
        src: nfs-server:/mnt/shared
        fstype: nfs
        state: mounted

    - name: add to fstab
      blockinfile:
         path: "/etc/fstab"
         block: |
                nfs-server:/mnt/shared   /mnt/shared  nfs defaults 0 0
